name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install FoundationDB
        run: |
          wget https://www.foundationdb.org/downloads/6.3.15/ubuntu/installers/foundationdb-clients_6.3.15-1_amd64.deb
          sudo dpkg -i foundationdb-clients_6.3.15-1_amd64.deb
          wget https://www.foundationdb.org/downloads/6.3.15/ubuntu/installers/foundationdb-server_6.3.15-1_amd64.deb
          sudo dpkg -i foundationdb-server_6.3.15-1_amd64.deb
      - name: Test rdb-analyzer
        run: |
          cd rdb-analyzer
          cargo test
          cargo test --features test-with-fdb
          cargo test --features test-with-sqlite -- --test-threads 1 # SQLite is currently broken with multiple threads
